- platform: mqtt
  name: "Bedroom outlet"
  state_topic: "home/bedroom/switch1"
  command_topic: "home/bedroom/switch1"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Heater"
  state_topic: "stat/sonoff/four_channel/POWER1"
  command_topic: "cmnd/sonoff/four_channel/power1"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Fan"
  state_topic: "stat/sonoff/four_channel/POWER1"
  command_topic: "cmnd/sonoff/four_channel/power1"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Living Room outlet 1"
  state_topic: "stat/sonoff/four_channel/POWER2"
  command_topic: "cmnd/sonoff/four_channel/power2"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Living Room outlet 2"
  state_topic: "stat/sonoff/four_channel/POWER3"
  command_topic: "cmnd/sonoff/four_channel/power3"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 
- platform: mqtt
  name: "Geyser"
  state_topic: "stat/sonoff/four_channel/POWER4"
  command_topic: "cmnd/sonoff/four_channel/power4"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 
- platform: mqtt
  name: "Kettle"
  state_topic: "stat/sonoff/pow/POWER"
  command_topic: "cmnd/sonoff/pow/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true 