- platform: mqtt
  name: "extractor fan"
  state_topic: "stat/sonoff/POWER"
  command_topic: "cmnd/sonoff/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "outlet_1"
  state_topic: "cmnd/bathroom/power"
  command_topic: "cmnd/bathroom/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "outlet_2"
  state_topic: "cmnd/kitchen/power"
  command_topic: "cmnd/kitchen/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Kettle"
  state_topic: "cmnd/bedroom/power"
  command_topic: "cmnd/bedroom/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true