- platform: mqtt
  name: "extractor fan"
  state_topic: "stat/fan/POWER"
  command_topic: "cmnd/fan/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Kettle"
  state_topic: "cmnd/kettle/power"
  command_topic: "cmnd/kettle/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true