- platform: mqtt
  name: "Bathroom Light"
  state_topic: "cmnd/bathroom/power"
  command_topic: "cmnd/bathroom/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Kitchen Light"
  state_topic: "cmnd/kitchen/power"
  command_topic: "cmnd/kitchen/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Bedroom Light"
  state_topic: "cmnd/bedroom/power"
  command_topic: "cmnd/bedroom/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true
- platform: mqtt
  name: "Living Room Light"
  state_topic: "cmnd/bedroom/power"
  command_topic: "cmnd/bedroom/power"
  payload_on: "ON"
  payload_off: "OFF"
  optimistic: false
  qos: 0
  retain: true