  broker: rsdatahost.local
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: homeassistant
  password: daver1ns
  protocol: 3.1
  birth_message:
    topic: "tele/hass1/LWT"
    payload: "Online"
    qos: 1
    retain: true
  will_message:
    topic: "tele/hass1/LWT"
    payload: "Offline"
    qos: 1
    retain: true