update_ha_config:
  alias: Update Config and Restart
  sequence:
    - service: shell_command.pull_config
    - delay:
        minutes: 2
    - service: homeassistant.restart

update_ha_source:
  alias: Update Source and Restart
  sequence:
    - service: shell_command.pull_source
    - delay:
        minutes: 15
    - service: homeassistant.restart

update_ha_scripts:
  alias: Update Scripts and Restart
  sequence:
    - service: shell_command.pull_scripts
    - delay:
        minutes: 1
    - service: homeassistant.restart
