sensor:
  - platform: moon
  - platform: yr
    monitored_conditions:
      - fog 
      - symbol

  - platform: darksky
    api_key: 0cf5544a1fd6e45e0dd1a4b650ebc6ae
    forecast:
      - 1
    monitored_conditions:
      - summary
      - hourly_summary
      - daily_summary
      - wind_speed
      - wind_bearing
      - precip_intensity
      - precip_probability
      - temperature
      - cloud_cover
      - temperature_max
      - temperature_min
  # Sun elevation
  - platform: template
    sensors:
      solar_angle:
        value_template: '{{ states.sun.sun.attributes.elevation }}'
        friendly_name: 'Solar angle'
        unit_of_measurement: 'degrees'

  # Sunset / Sunrise
  - platform: template
    sensors:
      sunset_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom("%I:%M") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunset"
        unit_of_measurement: "PM"

  - platform: template
    sensors:
      sunrise_time:
        value_template: '{% set timestamp = as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom("%I:%M") %} {{ timestamp.lstrip("0") }}'
        friendly_name: "Sunrise"
        unit_of_measurement: "AM"
  # Convert the Wind Direction from degrees to cardinal
  - platform: template
    sensors:
      friendly_wind_direction:
        friendly_name: 'Wind Direction'
        value_template: >-
          {%if states.sensor.dark_sky_wind_bearing.state | float<=11 %}N
          {% elif states.sensor.dark_sky_wind_bearing.state | float>348 %}N
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=34 | float>11 %}NNE
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=56 | float>34 %}NE
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=79 | float>56 %}ENE
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=101 | float>79 %}E
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=124 | float>101 %}ESE
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=146 | float>124 %}SE
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=169 | float>146 %}SSE
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=191 | float>169 %}S
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=214 | float>191 %}SSW
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=236 | float>214 %}SW
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=259 | float>236 %}WSW
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=281 | float>259 %}W
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=304 | float>281 %}WNW
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=326 | float>304 %}NW
          {% elif states.sensor.dark_sky_wind_bearing.state | float<=348 | float>326 %}NNW
          {%- endif %}
  - platform: template
    sensors:
      friendly_wind_direction_forecast:
        friendly_name: 'Wind Forecast'
        value_template: >-
          {%if states.sensor.dark_sky_wind_bearing_1.state | float<=11 %}N
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float>348 %}N
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=34 | float>11 %}NNE
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=56 | float>34 %}NE
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=79 | float>56 %}ENE
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=101 | float>79 %}E
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=124 | float>101 %}ESE
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=146 | float>124 %}SE
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=169 | float>146 %}SSE
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=191 | float>169 %}S
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=214 | float>191 %}SSW
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=236 | float>214 %}SW
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=259 | float>236 %}WSW
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=281 | float>259 %}W
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=304 | float>281 %}WNW
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=326 | float>304 %}NW
          {% elif states.sensor.dark_sky_wind_bearing_1.state | float<=348 | float>326 %}NNW
          {%- endif %}
  - platform: template
    sensors:
      friendly_date:
        friendly_name: "Today's Date"
        value_template: "{{ now().strftime('%A %B %e, %Y') }}"



group:
  Weather:
    entities:
      - group.weatherbadges
      - group.weatherconditionsbadges
      - sensor.dark_sky_daily_summary
      - group.weatherforecastbadges
  Today:
    entities:
      - group.weathertodaybadges
      - sensor.friendly_date
      - sensor.dark_sky_hourly_summary
  TodayWeather:
    name: "Today's Weather"
    entities:
      - group.weatherbadges
      - group.weatherconditionsbadges
      - sensor.dark_sky_daily_summary
  weathertodaybadges:
    entities:
      - sun.sun
      - sensor.sunrise_time
      - sensor.sunset_time
      - sensor.moon
  weatherbadges:
    entities:
      - sensor.yr_symbol
      - sensor.dark_sky_temperature
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
  weatherconditionsbadges:
    entities:
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_cloud_coverage
      - sensor.yr_fog
      - sensor.friendly_wind_direction
      - sensor.dark_sky_wind_speed
  weatherforecastbadges:
    entities:
      - sensor.dark_sky_daily_high_temperature_1
      - sensor.dark_sky_daily_low_temperature_1
      - sensor.dark_sky_precip_probability_1
      - sensor.dark_sky_cloud_coverage_1
      - sensor.friendly_wind_direction_forecast
homeassistant:
  customize_glob:
      group.weather*:
        custom_ui_state_card: custom-ui  
        state_card_mode: badges
  customize:
    sensor.solar_angle:
      unit_of_measurement: "°"
      icon: mdi:triangle-outline
    sensor.yr_symbol:
      friendly_name: " "
    sensor.dark_sky_hourly_summary:
      friendly_name: "Current:"
    sensor.dark_sky_daily_summary:
      friendly_name: "Forecast:"
    sensor.dark_sky_temperature:
      friendly_name: Current Temp
    sensor.dark_sky_daily_high_temperature:
      friendly_name: High
    sensor.dark_sky_daily_high_temperature_1:
      friendly_name: Forecast High
    sensor.dark_sky_daily_low_temperature:
      friendly_name: Low
    sensor.dark_sky_daily_low_temperature_1:
      friendly_name: Forecast Low
    sensor.dark_sky_precip_probability:
      friendly_name: Rain
    sensor.dark_sky_precip_probability_1:
      friendly_name: Forecast Rain
    sensor.dark_sky_cloud_coverage:
      friendly_name: Cloud
    sensor.dark_sky_wind_speed:
      friendly_name: Wind
    sensor.dark_sky_wind_bearing:
      friendly_name: Wind Bearing
    sensor.dark_sky_cloud_coverage_1:
      friendly_name: Forecast Cloud
    sensor.yr_fog:
      friendly_name: Fog
      icon: mdi:weather-fog
    sensor.friendly_date:
      icon: mdi:calendar